[tool.poetry]
name = "testechnique"
version = "0.1.0"
description = ""
authors = ["AdScientiam"]

[tool.poetry.dependencies]
python = "^3.10"
aiofiles = "^24.1.0"
ipykernel = "^6.29.5"
jupyter = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
